export const CARD_LIST_REQUEST = "CARD_LIST_REQUEST";
export const CARD_LIST_SUCCESS = "CARD_LIST_SUCCESS";
export const CARD_LIST_FAIL = "CARD_LIST_FAIL";
export const CARD_LIST_RESET = "CARD_LIST_RESET";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_RESET = "USER_REGISTER_RESET";

export const USER_DETAILS_REQUEST = "USER_DETAIL_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAIL_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAIL_FAIL";
export const USER_DETAILS_RESET = "USER_DETAIL_RESET";

export const USER_PROFILE_UPDATE_REQUEST = "USER_PROFILE_UPDATE_REQUEST";
export const USER_PROFILE_UPDATE_SUCCESS = "USER_PROFILE_UPDATE_SUCCESS";
export const USER_PROFILE_UPDATE_FAIL = "USER_PROFILE_UPDATE_FAIL";
export const USER_PROFILE_UPDATE_RESET = "USER_PROFILE_UPDATE_RESET";

export const USER_DETAILS_UPDATE_REQUEST = "USER_DETAILS_UPDATE_REQUEST";
export const USER_DETAILS_UPDATE_SUCCESS = "USER_DETAILS_UPDATE_SUCCESS";
export const USER_DETAILS_UPDATE_FAIL = "USER_DETAILS_UPDATE_FAIL";
export const USER_DETAILS_UPDATE_RESET = "USER_DETAILS_UPDATE_RESET";

export const NEW_MATCHES_LIST_REQUEST = "NEW_MATCHES_LIST_REQUEST";
export const NEW_MATCHES_LIST_SUCCESS = "NEW_MATCHES_LIST_SUCCESS";
export const NEW_MATCHES_LIST_FAIL = "NEW_MATCHES_LIST_FAIL";
export const NEW_MATCHES_LIST_RESET = "NEW_MATCHES_LIST_RESET";

export const LIKES_LIST_REQUEST = "LIKES_LIST_REQUEST";
export const LIKES_LIST_SUCCESS = "LIKES_LIST_SUCCESS";
export const LIKES_LIST_FAIL = "LIKES_LIST_FAIL";
export const LIKES_LIST_RESET = "LIKES_LIST_RESET";
