# Generated by Django 3.1.7 on 2021-04-02 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210402_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birthDate',
            new_name='birth_date'
        ),
        migrations.RenameField(
            model_name='user',
            old_name='shortBio',
            new_name='short_bio'
        ),
        migrations.RenameField(
            model_name='user',
            old_name='detailBio',
            new_name='detail_bio'
        ),
        migrations.RenameField(
            model_name='chatroom',
            old_name='matchedAt',
            new_name='matched_at'
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sentAt',
            new_name='sent_at'
        ),
    ]
