# Generated by Django 3.1.7 on 2021-04-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210405_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='short_bio',
            new_name='profession',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='detail_bio',
            new_name='self_introduction',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
        migrations.AddField(
            model_name='user',
            name='gender_identity',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sexual_preference',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others'), ('All', 'All')], default='All', max_length=30, null=True),
        ),
    ]
