# Generated by Django 3.1.7 on 2021-04-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210407_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='good',
            field=models.BooleanField(default=False),
        ),
    ]
